---
- name: Disable IPv6
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    sysctl_set: true
    reload: true
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Install haproxy
  ansible.builtin.apt:
    name: haproxy
    state: present
    update_cache: true

- name: Install rclone
  ansible.builtin.apt:
    name: rclone
    state: present

- name: Set qdisc
  ansible.posix.sysctl:
    name: net.core.default_qdisc
    value: fq
    sysctl_set: true
    state: present
    reload: true
  register: qdisc_result

- name: Set BBR
  ansible.posix.sysctl:
    name: net.ipv4.tcp_congestion_control
    value: bbr
    sysctl_set: true
    state: present
    reload: true
  when: qdisc_result is success

- name: Deploy haproxy.cfg
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "0644"
    validate: haproxy -c -f %s
  notify: Restart haproxy service

- name: Ensure haproxy is running
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true

- name: Ensure curl present
  ansible.builtin.package:
    name: curl
    state: present

- name: Download x-ui install script
  ansible.builtin.get_url:
    url: "{{ xui_control_script_url }}"
    dest: /tmp/install_x_ui.sh
    mode: '0755'

- name: Execute x-ui install script
  ansible.builtin.command: "/tmp/install_x_ui.sh {{ xui_control_version }}"
  args:
    creates: /usr/local/x-ui
  notify: Restart haproxy service

- name: Deploy x-ui unit
  ansible.builtin.template:
    src: x-ui.service.j2
    dest: /etc/systemd/system/x-ui.service
    mode: "0644"
  notify:
    - Restart x-ui service

- name: Clean up install script
  ansible.builtin.file:
    path: /tmp/install_x_ui.sh
    state: absent
